select * from customer limit 20

--q1 What is the total revenue generated by the male vs female customer?
select gender, Sum(purchase_amount) AS revenue
from customer
group by gender

--Q2 Which customers used a discount but still spend more than average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied='Yes' and purchase_amount>=(select AVG(purchase_amount) from customer)

--Q3 Which are the 5 highest products with the highest average review rating?
select item_purchased, ROUND(AVG(review_rating::numeric),2) AS "Average Review Rating"
from customer
group by item_purchased
Order by avg(review_rating) DESC
Limit 5

--Q4 Compare the average purchase amounts betweeen standard and express shipping
select shipping_type, 
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type

--Q5 Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non- subscribers
select subscription_status,
count (customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

--Q6 Which 5 products have the highest percentage of purchases with discounts applied?
--(means: which products rely heavily on discounts to sell)
select item_purchased,
ROUND(100* SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

--Q7 Segment customers into new, returning and loyal based on their total number of 
--previous purchases, and show the count of each segment.
with customer_type as(
select customer_id, previous_purchases,
    CASE
	when previous_purchases=1 then 'New'
	when previous_purchases between 2 and 10 then 'returning'
	else 'loyal'
	end as customer_segment
	from customer
)
select customer_segment,count(*) as"number of customer"
from customer_type
group by customer_segment

--Q8 What are the top 3 products sold within each category
with item_count as(
select category, item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id)DESC) as item_rank
from customer
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_count
where item_rank<=3;

--Q9 Are customers who are repeated buyers(more than 5 previous purchases) also likely to subscribe?
--(if repeated buyers are subscribers, it means it is great for business but if they are not then it means
-- that subscription policy is  ot attractive enough)
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases>5
group by subscription_status

--Q10 What is the revenue contribution of each age group?
select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;